### ISSUE TITLE
Annotorious icons are not visible and state remains as promise

### ISSUE THREAD

**Issue by AdamOrHd123** [recogito/annotorious-openseadragon#49] opened 2021-05-09 18:06 UTC
I'm trying to use the plug-in.
I'm calling:
var anno = OpenSeadragon.Annotorious(myViewer);
This creates an object
Afterwards, I call:
anno.loadAnnotations('annotations.w3c.json');
But this Promise object remains pending

I don't see any icons to use for annotation.
I'm missing something and would really appreciate some guidance.
Regards

**Comment by rsimon** [comment] 2021-05-09 19:29
The icons are not part of Annotorious. You'll need the [toolbar plugin](https://github.com/recogito/recogito-client-plugins/tree/main/packages/annotorious-toolbar) for that.

Regarding the annotations: where are you loading the file from? Does this file exist at the root folder of your app? What do the error and network consoles say? Are serving this from a web server, or did you just open the HTML file? (In the latter case, your browser will be blocking access due to the standard security policy. You'll need to start a local HTTP server to get around this.)

**Comment by rsimon** [comment] 2021-06-06 06:56
Closing this since it couldn't be reproduced & no further activity for a month. If you keep seeing the issue, feel free to re-open. In that case, please provide info on

- Annotorious version
- Browser
- OS
- As much info about your Annotorious init code and setup (loading from files vs. Webserver etc.) as possible

**Closed by rsimon** 2021-06-06 06:56 UTC
