### ISSUE TITLE
"disableSelect" from constructor does not affect anno.disableSelect property

### ISSUE THREAD

**Issue by EmKarr** [recogito/annotorious-openseadragon#141] opened 2022-08-25 14:09 UTC
Even though I set the "disableSelect" in the OSD-annotorious constructor, "anno.disableSelect" is "undefined" until I set it directly.

Best,
Michael

**Comment by rsimon** [comment] 2022-08-27 12:09
Transferring, because this is about the OSD version.

**Comment by rsimon** [comment] 2022-08-27 12:11
Duplicate of #135. Already fixed & will go live with the next release.

**Closed by rsimon** 2022-08-27 12:11 UTC
Labels: bug
